# Generated by Django 5.2.3 on 2025-06-19 15:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_claimauditlog_claimdocument_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_number", models.CharField(max_length=20, unique=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("revenue_summary", "Revenue Summary"),
                            ("payment_analysis", "Payment Analysis"),
                            ("insurance_claims", "Insurance Claims Report"),
                            ("patient_aging", "Patient Aging Report"),
                            ("service_performance", "Service Performance"),
                            ("doctor_revenue", "Doctor Revenue Report"),
                            ("monthly_summary", "Monthly Financial Summary"),
                            ("yearly_summary", "Yearly Financial Summary"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("report_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "export_file",
                    models.FileField(
                        blank=True, null=True, upload_to="financial_reports/%Y/%m/"
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        blank=True, help_text="pdf, xlsx, csv", max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenueMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "cash_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "insurance_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("total_invoices", models.IntegerField(default=0)),
                ("paid_invoices", models.IntegerField(default=0)),
                ("pending_invoices", models.IntegerField(default=0)),
                ("overdue_invoices", models.IntegerField(default=0)),
                ("total_payments", models.IntegerField(default=0)),
                (
                    "total_refunds",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_outstanding",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "top_services",
                    models.JSONField(default=list, help_text="Top performing services"),
                ),
                (
                    "service_revenue_breakdown",
                    models.JSONField(
                        default=dict, help_text="Revenue by service category"
                    ),
                ),
                (
                    "doctor_revenue_breakdown",
                    models.JSONField(default=dict, help_text="Revenue by doctor"),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "unique_together": {("period_type", "period_start", "period_end")},
            },
        ),
    ]
