# Generated by Django 5.2.3 on 2025-06-19 15:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_financialreport_revenuemetrics"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("invoice_created", "Invoice Created"),
                            ("invoice_sent", "Invoice Sent"),
                            ("payment_received", "Payment Received"),
                            ("payment_reminder", "Payment Reminder"),
                            ("overdue_notice", "Overdue Notice"),
                            ("final_notice", "Final Notice"),
                            ("payment_failed", "Payment Failed"),
                            ("refund_processed", "Refund Processed"),
                            ("insurance_claim_update", "Insurance Claim Update"),
                            ("billing_statement", "Billing Statement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("subject_template", models.CharField(max_length=200)),
                ("email_template", models.TextField()),
                ("sms_template", models.TextField(blank=True)),
                (
                    "available_variables",
                    models.JSONField(
                        default=list, help_text="List of available template variables"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("send_immediately", models.BooleanField(default=True)),
                (
                    "delay_hours",
                    models.IntegerField(default=0, help_text="Hours to delay sending"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["template_type", "name"],
                "unique_together": {("template_type", "is_default")},
            },
        ),
        migrations.CreateModel(
            name="NotificationSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("payment_reminder", "Payment Reminder"),
                            ("overdue_notice", "Overdue Notice"),
                            ("final_notice", "Final Notice"),
                            ("follow_up", "Follow-up"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "days_after_due",
                    models.IntegerField(help_text="Days after due date to trigger"),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("mail", "Physical Mail"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_notifications",
                    models.IntegerField(
                        default=3, help_text="Maximum notifications per invoice"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.notificationtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["days_after_due"],
            },
        ),
        migrations.CreateModel(
            name="BillingNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notification_number", models.CharField(max_length=20, unique=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("invoice_created", "Invoice Created"),
                            ("invoice_sent", "Invoice Sent"),
                            ("payment_received", "Payment Received"),
                            ("payment_reminder", "Payment Reminder"),
                            ("overdue_notice", "Overdue Notice"),
                            ("final_notice", "Final Notice"),
                            ("payment_failed", "Payment Failed"),
                            ("refund_processed", "Refund Processed"),
                            ("insurance_claim_update", "Insurance Claim Update"),
                            ("billing_statement", "Billing Statement"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("mail", "Physical Mail"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("recipient_phone", models.CharField(blank=True, max_length=20)),
                ("recipient_address", models.TextField(blank=True)),
                (
                    "scheduled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                ("delivery_response", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "insurance_claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="billing.insuranceclaim",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="billing.invoice",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_notifications",
                        to="patients.patient",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="billing.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "notification_type"],
                        name="billing_bil_patient_4fb772_idx",
                    ),
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="billing_bil_status_73aaf9_idx",
                    ),
                    models.Index(
                        fields=["invoice", "notification_type"],
                        name="billing_bil_invoice_346f9f_idx",
                    ),
                ],
            },
        ),
    ]
