# Generated by Django 5.2.3 on 2025-06-19 16:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_notificationtemplate_notificationschedule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tier_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                            ("vip", "VIP"),
                            ("insurance", "Insurance"),
                            ("self_pay", "Self Pay"),
                            ("employee", "Employee"),
                            ("senior", "Senior Citizen"),
                            ("student", "Student"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "markup_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("minimum_age", models.IntegerField(blank=True, null=True)),
                ("maximum_age", models.IntegerField(blank=True, null=True)),
                ("requires_verification", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority tiers are applied first"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="BundleService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "individual_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DynamicPricingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("time_based", "Time Based"),
                            ("demand_based", "Demand Based"),
                            ("seasonal", "Seasonal"),
                            ("volume_based", "Volume Based"),
                            ("loyalty_based", "Loyalty Based"),
                            ("emergency", "Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "conditions",
                    models.JSONField(
                        default=dict, help_text="Rule conditions and parameters"
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed Amount"),
                            ("multiplier", "Multiplier"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "adjustment_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "minimum_adjustment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "maximum_adjustment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pricing_rules",
                        to="billing.servicecategory",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="pricing_rules", to="billing.service"
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="ServiceBundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("bundle_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "individual_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sum of individual service prices",
                        max_digits=10,
                    ),
                ),
                (
                    "savings_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "savings_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="bundles",
                        through="billing.BundleService",
                        to="billing.service",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="bundleservice",
            name="bundle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="billing.servicebundle"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bundleservice",
            unique_together={("bundle", "service")},
        ),
        migrations.CreateModel(
            name="ServicePricing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "minimum_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "maximum_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("effective_from", models.DateField(default=django.utils.timezone.now)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pricing_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_pricing",
                        to="billing.pricingtier",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_tiers",
                        to="billing.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from"],
                "unique_together": {("service", "pricing_tier", "effective_from")},
            },
        ),
    ]
