# Generated by Django 5.2.3 on 2025-06-18 16:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("patient_id", models.CharField(max_length=20, unique=True)),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Height in cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                            ("separated", "Separated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("employer", models.CharField(blank=True, max_length=100)),
                (
                    "allergies",
                    models.TextField(blank=True, help_text="List of known allergies"),
                ),
                (
                    "chronic_conditions",
                    models.TextField(
                        blank=True, help_text="List of chronic medical conditions"
                    ),
                ),
                (
                    "current_medications",
                    models.TextField(
                        blank=True, help_text="Current medications and dosages"
                    ),
                ),
                ("family_medical_history", models.TextField(blank=True)),
                (
                    "registration_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the patient"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["patient_id"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceInformation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("tertiary", "Tertiary"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("provider_name", models.CharField(max_length=100)),
                ("policy_number", models.CharField(max_length=50)),
                ("group_number", models.CharField(blank=True, max_length=50)),
                ("subscriber_name", models.CharField(max_length=100)),
                ("subscriber_id", models.CharField(max_length=50)),
                (
                    "relationship_to_subscriber",
                    models.CharField(default="self", max_length=50),
                ),
                ("effective_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "copay_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "deductible_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("provider_phone", models.CharField(blank=True, max_length=17)),
                ("provider_address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_info",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["insurance_type", "provider_name"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("parent", "Parent"),
                            ("child", "Child"),
                            ("sibling", "Sibling"),
                            ("friend", "Friend"),
                            ("guardian", "Guardian"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "primary_phone",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["patient_id"], name="patients_pa_patient_927c52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["user"], name="patients_pa_user_id_b78fa3_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["registration_date"], name="patients_pa_registr_b5cb97_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="insuranceinformation",
            unique_together={("patient", "insurance_type")},
        ),
    ]
