# Generated by Django 5.2.3 on 2025-06-19 16:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "appointments",
            "0002_recurringpattern_appointment_cancellation_reason_and_more",
        ),
        ("billing", "0006_pricingtier_bundleservice_dynamicpricingrule_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("smtp", "SMTP Server"),
                            ("sendgrid", "SendGrid"),
                            ("mailgun", "Mailgun"),
                            ("ses", "Amazon SES"),
                            ("postmark", "Postmark"),
                            ("mandrill", "Mandrill"),
                            ("sparkpost", "SparkPost"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, help_text="Provider-specific configuration"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "daily_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Daily email limit", null=True
                    ),
                ),
                (
                    "hourly_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Hourly email limit", null=True
                    ),
                ),
                ("emails_sent_today", models.PositiveIntegerField(default=0)),
                ("emails_sent_this_hour", models.PositiveIntegerField(default=0)),
                (
                    "last_reset_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "last_reset_hour",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmailAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("emails_sent", models.PositiveIntegerField(default=0)),
                ("emails_delivered", models.PositiveIntegerField(default=0)),
                ("emails_opened", models.PositiveIntegerField(default=0)),
                ("emails_clicked", models.PositiveIntegerField(default=0)),
                ("emails_bounced", models.PositiveIntegerField(default=0)),
                ("emails_failed", models.PositiveIntegerField(default=0)),
                ("emails_spam", models.PositiveIntegerField(default=0)),
                ("emails_unsubscribed", models.PositiveIntegerField(default=0)),
                (
                    "template_metrics",
                    models.JSONField(
                        default=dict, help_text="Metrics broken down by template type"
                    ),
                ),
                (
                    "provider_metrics",
                    models.JSONField(
                        default=dict, help_text="Metrics broken down by email provider"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("appointment_confirmation", "Appointment Confirmation"),
                            ("appointment_reminder", "Appointment Reminder"),
                            ("appointment_cancellation", "Appointment Cancellation"),
                            ("appointment_rescheduled", "Appointment Rescheduled"),
                            ("test_results_ready", "Test Results Ready"),
                            ("prescription_ready", "Prescription Ready"),
                            ("payment_confirmation", "Payment Confirmation"),
                            ("payment_reminder", "Payment Reminder"),
                            ("invoice_generated", "Invoice Generated"),
                            ("insurance_claim_update", "Insurance Claim Update"),
                            ("welcome_patient", "Welcome New Patient"),
                            ("welcome_doctor", "Welcome New Doctor"),
                            ("password_reset", "Password Reset"),
                            ("account_activation", "Account Activation"),
                            ("system_maintenance", "System Maintenance"),
                            ("emergency_alert", "Emergency Alert"),
                            ("custom", "Custom Template"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "subject_template",
                    models.CharField(
                        help_text="Subject line with variable placeholders",
                        max_length=500,
                    ),
                ),
                (
                    "html_template",
                    models.TextField(
                        help_text="HTML email template with variable placeholders"
                    ),
                ),
                (
                    "text_template",
                    models.TextField(
                        help_text="Plain text email template with variable placeholders"
                    ),
                ),
                (
                    "available_variables",
                    models.JSONField(
                        default=list,
                        help_text="List of available variables for this template",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default template for this type"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["template_type", "name"],
                "unique_together": {("template_type", "is_default")},
            },
        ),
        migrations.CreateModel(
            name="EmailSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("appointment_reminders", "Appointment Reminders"),
                            ("test_results", "Test Results"),
                            ("payment_reminders", "Payment Reminders"),
                            ("promotional", "Promotional Emails"),
                            ("newsletters", "Newsletters"),
                            ("system_updates", "System Updates"),
                            ("emergency_alerts", "Emergency Alerts"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_subscribed", models.BooleanField(default=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                            ("monthly", "Monthly Digest"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "subscription_type"],
                "unique_together": {("user", "subscription_type")},
            },
        ),
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_id",
                    models.CharField(
                        help_text="Human-readable notification ID",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("recipient_name", models.CharField(blank=True, max_length=200)),
                ("subject", models.CharField(max_length=500)),
                ("html_content", models.TextField()),
                ("text_content", models.TextField()),
                (
                    "template_variables",
                    models.JSONField(
                        default=dict, help_text="Variables used to render the template"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, help_text="When to send the email", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                            ("spam", "Marked as Spam"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("bounce_reason", models.TextField(blank=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=200)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_notifications",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_email_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_notifications",
                        to="billing.invoice",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.emailtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_email", "status"],
                        name="notificatio_recipie_afcb8b_idx",
                    ),
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="notificatio_status_70e5c9_idx",
                    ),
                    models.Index(
                        fields=["template", "status"],
                        name="notificatio_templat_cddc15_idx",
                    ),
                ],
            },
        ),
    ]
