# Generated by Django 5.2.3 on 2025-06-19 16:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0002_recurringpattern_appointment_cancellation_reason_and_more",
        ),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("twilio", "Twilio"),
                            ("aws_sns", "Amazon SNS"),
                            ("nexmo", "Nexmo/Vonage"),
                            ("messagebird", "MessageBird"),
                            ("clicksend", "ClickSend"),
                            ("textlocal", "Textlocal"),
                            ("plivo", "Plivo"),
                            ("mock", "Mock Provider (Testing)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, help_text="Provider-specific configuration"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "daily_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Daily SMS limit", null=True
                    ),
                ),
                (
                    "hourly_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Hourly SMS limit", null=True
                    ),
                ),
                (
                    "cost_per_sms",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("sms_sent_today", models.PositiveIntegerField(default=0)),
                ("sms_sent_this_hour", models.PositiveIntegerField(default=0)),
                (
                    "total_cost_today",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "last_reset_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "last_reset_hour",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SMSAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("sms_sent", models.PositiveIntegerField(default=0)),
                ("sms_delivered", models.PositiveIntegerField(default=0)),
                ("sms_failed", models.PositiveIntegerField(default=0)),
                ("sms_undelivered", models.PositiveIntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "template_metrics",
                    models.JSONField(
                        default=dict, help_text="Metrics broken down by template type"
                    ),
                ),
                (
                    "provider_metrics",
                    models.JSONField(
                        default=dict, help_text="Metrics broken down by SMS provider"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="SMSTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("appointment_reminder", "Appointment Reminder"),
                            ("appointment_confirmation", "Appointment Confirmation"),
                            ("appointment_cancellation", "Appointment Cancellation"),
                            ("test_results_ready", "Test Results Ready"),
                            ("prescription_ready", "Prescription Ready"),
                            ("payment_reminder", "Payment Reminder"),
                            ("payment_confirmation", "Payment Confirmation"),
                            ("emergency_alert", "Emergency Alert"),
                            ("verification_code", "Verification Code"),
                            ("password_reset", "Password Reset"),
                            ("appointment_today", "Appointment Today"),
                            ("medication_reminder", "Medication Reminder"),
                            ("custom", "Custom Template"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "message_template",
                    models.TextField(
                        help_text="SMS message template with variable placeholders (max 1600 chars for 10 SMS)",
                        max_length=1600,
                    ),
                ),
                (
                    "available_variables",
                    models.JSONField(
                        default=list,
                        help_text="List of available variables for this template",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default template for this type"
                    ),
                ),
                (
                    "max_length",
                    models.PositiveIntegerField(
                        default=160, help_text="Maximum message length"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["template_type", "name"],
                "unique_together": {("template_type", "is_default")},
            },
        ),
        migrations.CreateModel(
            name="SMSNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_id",
                    models.CharField(
                        help_text="Human-readable notification ID",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        help_text="Phone number in E.164 format", max_length=20
                    ),
                ),
                ("recipient_name", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField(max_length=1600)),
                (
                    "template_variables",
                    models.JSONField(
                        default=dict, help_text="Variables used to render the template"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, help_text="When to send the SMS", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("undelivered", "Undelivered"),
                            ("unknown", "Unknown"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("provider_message_id", models.CharField(blank=True, max_length=200)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_notifications",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sms_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.smstemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_phone", "status"],
                        name="notificatio_recipie_5daefb_idx",
                    ),
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="notificatio_status_2cf900_idx",
                    ),
                    models.Index(
                        fields=["template", "status"],
                        name="notificatio_templat_6ffe61_idx",
                    ),
                ],
            },
        ),
    ]
