# Generated by Django 5.2.3 on 2025-06-19 17:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_pushnotificationconfiguration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateLanguage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Language code (e.g., en, es, fr)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Language name (e.g., English, Spanish)",
                        max_length=100,
                    ),
                ),
                (
                    "native_name",
                    models.CharField(
                        help_text="Native language name (e.g., Español)", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "text_direction",
                    models.CharField(
                        choices=[("ltr", "Left to Right"), ("rtl", "Right to Left")],
                        default="ltr",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateVariable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "variable_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("datetime", "Date Time"),
                            ("boolean", "Boolean"),
                            ("email", "Email"),
                            ("phone", "Phone Number"),
                            ("url", "URL"),
                            ("currency", "Currency"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                (
                    "format_type",
                    models.CharField(
                        choices=[
                            ("none", "No Formatting"),
                            ("uppercase", "Uppercase"),
                            ("lowercase", "Lowercase"),
                            ("title_case", "Title Case"),
                            ("date_short", "Short Date (MM/DD/YYYY)"),
                            ("date_long", "Long Date (Month DD, YYYY)"),
                            ("time_12h", "12-hour Time"),
                            ("time_24h", "24-hour Time"),
                            ("currency_usd", "US Dollar ($)"),
                            ("phone_us", "US Phone Format"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("default_value", models.TextField(blank=True)),
                (
                    "validation_regex",
                    models.CharField(
                        blank=True,
                        help_text="Regex pattern for validation",
                        max_length=500,
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UnifiedTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("appointment_confirmation", "Appointment Confirmation"),
                            ("appointment_reminder", "Appointment Reminder"),
                            ("appointment_cancellation", "Appointment Cancellation"),
                            ("test_results_ready", "Test Results Ready"),
                            ("prescription_ready", "Prescription Ready"),
                            ("payment_confirmation", "Payment Confirmation"),
                            ("payment_reminder", "Payment Reminder"),
                            ("invoice_generated", "Invoice Generated"),
                            ("welcome_patient", "Welcome New Patient"),
                            ("welcome_doctor", "Welcome New Doctor"),
                            ("password_reset", "Password Reset"),
                            ("verification_code", "Verification Code"),
                            ("emergency_alert", "Emergency Alert"),
                            ("system_maintenance", "System Maintenance"),
                            ("custom", "Custom Template"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "supported_channels",
                    models.JSONField(
                        default=list,
                        help_text="List of supported notification channels",
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.unifiedtemplate",
                    ),
                ),
                (
                    "variables",
                    models.ManyToManyField(
                        related_name="templates", to="notifications.templatevariable"
                    ),
                ),
            ],
            options={
                "ordering": ["template_type", "name"],
                "unique_together": {("template_type", "is_default")},
            },
        ),
        migrations.CreateModel(
            name="TemplateUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel", models.CharField(max_length=20)),
                ("variables_used", models.JSONField(default=dict)),
                ("render_time_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.templatelanguage",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="notifications.unifiedtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["template", "channel"],
                        name="notificatio_templat_d81ad5_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_aeed70_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TemplateContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("email_subject", "Email Subject"),
                            ("email_html", "Email HTML"),
                            ("email_text", "Email Text"),
                            ("sms_message", "SMS Message"),
                            ("push_title", "Push Title"),
                            ("push_body", "Push Body"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "properties",
                    models.JSONField(
                        default=dict,
                        help_text="Additional properties (e.g., icon_url for push)",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.templatelanguage",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="notifications.unifiedtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["template", "language", "content_type"],
                "unique_together": {("template", "language", "content_type")},
            },
        ),
    ]
